package templates

var Header = `
// Code generated by gosoap DO NOT EDIT.

package {{.}}

import (
	"encoding/xml"
	"time"

	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string ` + "`" + `xml:",innerxml"` + "`" + `
}

type AnyURI string

type NCName string

`
